### ISSUE TITLE
Task 8 Prerequisites

### ISSUE THREAD

**Issue by maksumov** [maksumov/rs-cart-api#2]
# Task 8 Definition

Task defined at https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task8-docker-elastic-beanstalk/task.md

## Task 8 prerequisites

- [x] install WSL on Windows 10 (ubuntu 20.04)
- [x] install docker & docker-compose in WSL/ubuntu
- [x] configure git under WSL/ubuntu
- [x] install node 12 under WSL/ubuntu
- [x] install AWS EB CLI ([Instructions](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html))

**Comment by maksumov** [comment]
# AWS EB CLI steps

```bash
sudo apt-get install build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
git clone git@github.com:aws/aws-elastic-beanstalk-cli-setup.git
sudo apt install python3-pip
pip3 install virtualenv
python3 aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
echo 'export PATH="~/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
echo 'alias python=python3' >> ~/.bash_aliases && source ~/.bash_aliases
echo 'alias pip=pip3' >> ~/.bash_aliases && source ~/.bash_aliases
sudo apt-get install python-is-python3
```

**Comment by maksumov** [comment]
https://askubuntu.com/questions/942930/usr-bin-env-python-no-such-file-or-directory

**Comment by maksumov** [comment]
# Steps for Ubuntu 18.04

```bash
sudo apt-get install build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
git clone git@github.com:aws/aws-elastic-beanstalk-cli-setup.git
sudo apt install python3-pip
pip3 install virtualenv

sudo rm /usr/bin/python
sudo ln -s /usr/bin/python3 /usr/bin/python
sudo ln -s /usr/bin/pip3 /usr/bin/pip

echo 'export PATH="~/.local/bin/:$PATH"' >> ~/.bash_profile && source ~/.bash_profile

python aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
echo 'export PATH="/home/master/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
```

**Comment by maksumov** [comment]
#  Steps to Downgrade to Node 12

Current installed node LTS version is 14.15. It makes sense to lower the node version to reduce memory consumption (requirements).

```bash
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get remove -y nodejs  # remove node 14.15
sudo apt-get install -y nodejs  # install node 12.20
node -v   # check node version
```

Source: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by maksumov** [comment]
# Install Docker engine on Ubuntu

```bash
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88   # check fingerprint
# pub   rsa4096 2017-02-22 [SCEA]
#       9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
# uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
# sub   rsa4096 2017-02-22 [S]

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

sudo docker run hello-world   # to verify that Docker Engine is installed correctly
```

Source: https://docs.docker.com/engine/install/ubuntu/

**Comment by maksumov** [comment]
# Docker post-installation steps for Linux

```bash
sudo groupadd docker  # Create the docker group.
sudo usermod -aG docker $USER  # Add your user to the docker group.

newgrp docker   # to activate the changes to groups
docker run hello-world  # Verify that you can run docker commands without sudo.

sudo chown "$USER":"$USER" /home/"$USER"/.docker -R 
sudo chmod g+rwx "$HOME/.docker" -R

sudo systemctl enable docker  # Configure Docker to start on boot
```

source: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by maksumov** [comment]
# Docker install & start in WSL (Ubuntu 20.04)

```bash
sudo apt-get remove docker docker.io containerd runc
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

sudo groupadd docker  # Create the docker group.
sudo usermod -aG docker $USER  # Add your user to the docker group.

newgrp docker   # to activate the changes to groups

apt-cache policy docker-ce
sudo service docker start
sudo service docker status
docker run hello-world
```

Adapted from instructions above as a base with instructions at these sources:

- https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04-ru
- https://stackoverflow.com/questions/52197246/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate
